version: '2.4'
services:
  storybook:
    build:
      context: .
      dockerfile: build/Dockerfile
      target: dev
    environment:
      - WEBPACK_WATCH_POLLING=1
      - PORT=6006
    ports:
      - 6006:6006
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: npm run storybook
    # note: running storybook will also build it,
    # a separate command is unnecessary
volumes:
  node_modules:
